app/urls.py
from django.urls import path
from . import views

from app.views import (

    RegisterView,
    LoginView,
    LogoutView,
    UserProfileView,
    UserProfileUpdateView,
    CartDetailView,
    cart_checkout,
    UserProfileUpdateView,
    index,
    article_detail,
    ReviewCreateView,
    index_review,
    add_to_cart,
    remove_from_cart,
    article_detail,
    ReviewCreateView,
    ReviewDeleteView
)

urlpatterns = [
    path('', index, name='index'),
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('userprofile/<int:pk>', UserProfileView.as_view(), name='user_profile'),
    path('userprofile/<int:pk>/edit', UserProfileUpdateView.as_view(), name='user_profile_edit'),
    path('article/<int:pk>', article_detail, name='article_detail'),
    path('article/<int:pk>/review/create', ReviewCreateView.as_view(), name='review_create'),
    path('article/<int:article_pk>/review/delete/<int:pk>', ReviewDeleteView.as_view(), name='review_delete'),
    path('cart/<int:pk>', CartDetailView.as_view(), name='cart_detail'),
    path('cart_checkout/<int:pk>', cart_checkout, name='cart_checkout'),
    path('article/<int:pk>/add', add_to_cart, name='add_to_cart'),
    path('article/<int:pk>/remove', remove_from_cart, name='remove_from_cart'),
    path('article/<int:pk>/index_review', index_review, name='index_review'),
]

fashionshop/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('app.urls')),
    path('admin/', admin.site.urls),
]

app/models.py
from django.contrib.auth import get_user_model
from django.db import models


User = get_user_model()

class UserProfile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='profile')
    birthday = models.DateField(blank=True, null=True)
    address = models.CharField(max_length=30, blank=True, null=True)
    credit = models.FloatField(default=0)


class Category(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class Article(models.Model):
    photo = models.FileField(upload_to='media/', blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=30)
    description = models.CharField(max_length=70)
    price = models.FloatField()


class Cart(models.Model):
    user_id = models.OneToOneField(User, on_delete=models.CASCADE)
    articles = models.ManyToManyField(Article, related_name='carts', blank=True)
    sum = models.FloatField()


class Review(models.Model):
    article= models.ForeignKey(Article, on_delete=models.CASCADE, related_name='article_reviews')
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name="reviews")
    text = models.CharField(max_length=30, blank=True, null=True)
    nota = models.IntegerField()

app/forms.py
from django import forms
from app import models


class UserProfileForm(forms.ModelForm):
    first_name = forms.CharField(max_length=100)
    last_name = forms.CharField(max_length=100)
    e_mail = forms.CharField(max_length=100)
    class Meta:
        model =models.UserProfile
        exclude = ['user']

app/templates/article_detail.html
{% extends 'base.html' %}

{% block title %}
{{ post.text }}
{% endblock%}

{% block content %}
<div class="container">
   <div class="row">
       <div class="p-3">
           <div class="card text-center" style="width: 18rem;">
               {% if article.photo %}
               <img class="card-img-top" src="{{ article.photo.url }}" alt="Article photo">
               {% endif %}
               <div class="card-body">
                   <h5 class="card-title">
                       {{ article.title }}
                   </h5>
                   <h6 class="card-subtitle">
                       {{ article.category }}
                   </h6>
                   <p class="card-text">
                       {{ article.description }}
                   </p>
                   <p class="card-text">
                       {{ article.price }}
                   </p>
               </div>
               <div class="card-footer text-center">
                   <a href="{% url 'add_to_cart' article.id %}" class="btn btn-lg btn-danger">Buy</a>
               </div>
           </div>
       </div>
   </div>
  <a href="{% url 'index_review' article.id %}" class="btn btn-primary">See reviews</a>
</div>
{% endblock %}

app/templates/base.html
{% load static %}
<html>
  <head>
    <title>
      {% block title %}
      {% endblock %}
    </title>

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
  </head>
  <body>
    {% include 'nav.html' %}

    {% block content %}
    {% endblock %}
  </body>
    {% block js %}
    {% endblock %}
</html>

app/templates/cart_detail.html
{% extends 'base.html' %}

{% block content %}
{% csrf_token %}
{% if cart.articles.count != 0 %}
<div class = "container">
    <table class="table table-hover">
        <thead class="thead-dark">
            <tr>
                <th>Product</th>
                <th>Quantity</th>
                <th>Total Price</th>
                <th>Options</th>
            </tr>
        </thead>
        <tbody>
            {% for item in cart.articles.all %}
            <tr>
                <td>{{ item.title }}</td>
                <td>{{ item.description }}</td>
                <td>{{ item.price }}</td>
                <td><a class="btn btn-primary" href="{% url 'remove_from_cart' item.id %}">Remove</a></td>
            </tr>
            {% endfor %}
            <tr> <td colspan="4">Total sum: {{ cart.sum }}</td> </tr>
         </tbody>
    </table>

     <a class="btn btn-primary" href="{% url 'cart_checkout' user.id %}">Checkout</a>
</div>
    {%else%}
        <div class = "container">
      <p>You don't have any products.</p>
        </div>
    {%endif%}
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}

{% block title %} ShopApp{% endblock %}

{% block content %}


  <div class="row container">
    {% for article in article_list %}
      <div class="col-sm-6 p-3">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">{{ article.title }}</h5>
              <h6 class="card-title">{{ article.description }}</h6>


            <a href="{% url 'article_detail' article.id %}" class="btn btn-primary">See article details</a>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
{% endblock %}

app/templates/index_review.html
{% extends 'base.html' %}

{% block title %} ShopApp{% endblock %}

{% block content %}


  <div class="row container">
    {% for rev in review_list %}
      <div class="col-sm-6 p-3">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">{{ rev.text }}</h5>
              <h6 class="card-title">{{ rev.nota }}</h6>
             <a href="{% url 'review_delete' article.id rev.id %}" class="btn btn-primary">Delete review</a>

          </div>
        </div>
      </div>
    {% endfor %}
       <a href="{% url 'review_create' article.id %}" class="btn btn-primary">Create review</a>

  </div>
{% endblock %}

app/templates/login.html
{% extends 'base.html' %}

{% block content %}
  <h2>Login</h2>
  <form method="post" class="col-6">
    {% csrf_token %}
    <div class="form-group">
        {{ form.errors }}
    </div>

    <div class="form-group">
      <label for="id_username">Username:</label>
      <input type="text" name="username" class="form-control" autofocus="" required="" id="id_username" maxlength="150">
    </div>

    <div class="form-group">
      <label for="id_password">Password:</label>
      <input type="password" name="password" class="form-control" required="" id="id_password">
    </div>

    <button class="btn btn-primary" type="submit">Login</button>
  </form>
{% endblock %}

app/templates/nav.html
<ul class="nav">


  {% if user.is_authenticated %}
    <li class="nav-item">
      <a class="nav-link active" href="{% url 'user_profile' user.id %}">Hello, {{ user.username }}</a>
    </li>

    <li class="nav-item">
      <a class="nav-link active" href="{% url 'index'%}">Products</a>
    </li>

    <li class="nav-item">
      <a class="nav-link active" href="{% url 'cart_detail' user.id %}">Cart</a>
    </li>
    {% if user.is_superuser %}
    <li class="nav-item">
      <a class="nav-link active" href="{% url 'admin:index' %}">Admin</a>
    </li>
    {% endif %}
    <li class="nav-item">
      <a class="nav-link active" href="{% url 'logout' %}">Logout</a>
    </li>
  {% else %}
    <li class="nav-item">
      <a class="nav-link active" href="{% url 'login' %}">Login</a>
    </li>
    <li class="nav-item">
      <a class="nav-link active" href="{% url 'register' %}">Register</a>
    </li>

  {% endif %}
  </ul>

app/templates/register.html
{% extends 'base.html' %}

{% block content %}
  <h2>Register</h2>
  <form method="post" class="col-6">
    {% csrf_token %}
    <div class="form-group">
        {{ form.errors }}
    </div>

    <div class="form-group">
      <label for="id_username">Username:</label>
      <input type="text" name="username" class="form-control" autofocus="" required="" id="id_username" maxlength="150">
    </div>

    <div class="form-group">
      <label for="id_password1">Password:</label>
      <input type="password" name="password1" class="form-control" required="" id="id_password1">
    </div>

    <div class="form-group">
      <label for="id_password2">Password confirmation:</label>
      <input type="password" name="password2" class="form-control" required="" id="id_password2">
    </div>

    <button class="btn btn-primary" type="submit">Register</button>
  </form>
{% endblock %}

app/templates/review_create.html
{% extends 'base.html' %}
{% block title %}
  Create review
{% endblock%}

{% block content %}
  <form method="post" class="form-inline justify-content-center" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group mx-2">
      <textarea rows="4" cols="50" class="form-control" type="text-area"
      name="text" required="" id="id_text" maxlength="200"></textarea>
    </div>
    <div class="form-group mx-2">
      <input type="number" name="nota" id="id_nota" min = "1" max="10">
    </div>
    <input class="btn btn-secondary" type="submit" value="Create review" />
  </form>
{% endblock %}

app/templates/review_delete.html
{% extends 'base.html' %}
{% block title %}
  Delete review
{% endblock%}

{% block content %}
<div class="container m-5">
  <h5>Are you sure you want to delete this review?</h5>
  <form method="post" class="form-inline">
    {% csrf_token %}
    <input class="btn btn-secondary" type="submit" value="Delete review" />
  </form>
</div>
{% endblock %}

app/templates/user_profile.html
{% extends 'base.html' %}

{% block title %} User Profile - {{ userprofile.user.username }} {% endblock %}

{% block content %}
  <div class="container">
    {% if user == userprofile.user %}
      <div class="m-2">
        <a class="btn btn-primary" href="{% url 'user_profile_edit' userprofile.id %}">Edit profile</a>
      </div>
    {% endif %}



    <h1>{{ userprofile.user.username }}' Profile</h1>
    {% if  user == userprofile.user %}
    <ul class="list-group m-4">
      <li class="list-group-item"><b>Fullname:</b> {{ userprofile.user.first_name }} {{ userprofile.user.last_name }}</li>
      <li class="list-group-item"><b>Username:</b> {{ userprofile.user.username }}</li>
      <li class="list-group-item"><b>E-mail:</b> {{ userprofile.user.email }}</li>
      <li class="list-group-item"><b>Birthday:</b> {{ userprofile.birthday }}</li>
      <li class="list-group-item"><b>Address:</b> {{ userprofile.address }}</li>
      <li class="list-group-item"><b>Credit:</b> {{ userprofile.credit }}</li>

    </ul>
    {% endif %}
  </div>
{% endblock %}

app/templates/user_profile_update.html
{% extends 'base.html' %}
{% block title %}
  Edit profile
{% endblock%}

{% block content %}
  <form method="post" class="justify-content-center col-6" enctype='multipart/form-data'>
    {% csrf_token %}
    {{ form.errors }}
    <div class="form-group mx-2">
      <label for="id_birthday">Birthday:</label>
      <input type="text" name="birthday" value="{{ form.birthday.initial | date:'Y-m-d' }}"
             id="id_birthday">
    </div>

    <div class="form-group mx-2">
      <label for="id_address">Address:</label>
      <textarea name="address" class="form-control" id="id_address" value="{{ form.address.initial }}">
      </textarea>
    </div>

    <div class="form-group mx-2">
      <label for="id_first_name">First name:</label>
      <input type="text" class="form-control" name="first_name" 
             value="{{ form.first_name.initial }}" required="" id="id_first_name" 
             maxlength="100">
    </div>

    <div class="form-group mx-2">
      <label for="id_last_name">Last name:</label>
      <input type="text" class="form-control" name="last_name" 
             required="" id="id_last_name" maxlength="100" 
             value="{{ form.last_name.initial }}">
    </div>

    <div class="form-group mx-2">
      <label for="id_e_mail">E-mail:</label>
      <input type="text"  class="form-control" name="e_mail" 
             required="" id="id_e_mail" maxlength="100"
             value="{{ form.e_mail.initial }}">
    </div>


    <div class="form-group mx-2">
      <label for="id_credit">Credit:</label>
      <input type="number" class="form-control" name="credit" id="id_credit" value="{{ form.credit.initial }}">
    </div>

    <input style="margin-top:20px;" class="btn btn-secondary" type="submit" value="Update profile" />
  </form>
{% endblock %}

{% block js %}
<script>
  $(".custom-file-input").on("change", function() {
    var fileName = $(this).val().split("\\").pop();
    $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
  });
</script>
{% endblock %}